### ISSUE TITLE
Don't work flag "Show line numbers by default" in settings.

### ISSUE THREAD

**Issue by mrBananza** [aramk/crayon-syntax-highlighter#294]
Hi! 

If I turn off flag "Show line numbers by default" in settings then line numbers disappear only in the example code.

Turn off "Show line numbers by default"

Settings screen:
![screen shot 2015-08-24 at 19 27 26](https://cloud.githubusercontent.com/assets/9636173/9445820/c7f4e7c0-4a96-11e5-8fc0-25e5c94271ac.png)

Page screen:
![screen shot 2015-08-24 at 19 31 04](https://cloud.githubusercontent.com/assets/9636173/9445844/f0f48194-4a96-11e5-8e78-bb32a7fde56b.png)

Line numbers do not disappear, but the flag is turned off.

Wordpress 2.7.1

**Comment by aramk** [comment]
WordPress 2.7.1 is quite outdated so that might be it, but what version of the plugin are you using? Verify that you can see `class="crayon-nums " data-settings="hide"` in the source code for the generated WordPress page. Do you see a `margin-left: -26px;` or similar on crayon-table when you're toggling line numbers manually? The same should occur when initially loading the page. Also check for any script errors in the JS console, as an error will halt the rest of the script.

**Comment by mrBananza** [comment]
Pardon me! I was not accurate!
I use wordpress 4.3 and version of  the plagin is 2.7.1. 
I checked console and found error that halt the script. Now everything works. Sorry for false alarm.

**Comment by aramk** [comment]
Awesome, nice work!
