### ISSUE TITLE
Add your own theme based on sublime .tmTheme?

### ISSUE THREAD

**Issue by dingo-d** [aramk/crayon-syntax-highlighter#332]
I have modified [OneDark theme](https://packagecontrol.io/packages/One%20Dark%20Material%20-%20Theme) for Sublime Text, and I really like that color scheme.

I have `.xml` file of that theme, and I noticed that you can create and edit the theme manually in Crayon, which is cool, but I was wondering if it's possible to pull the colors from the `.xml` file to the theme somehow? It would speed up the matching process greatly.

**Comment by aramk** [comment]
Looks nice. The best way is really to use the interactive Theme Editor. It lets you choose the colours and adjust them. Two text editors will likely have different element names though. I'm aware of a Textmate standard which I based my own elements on, but I don't have plans to add support for importing from external formats at the moment. The theme editor should do the job in a minute or two, since it has live updates.

**Comment by dingo-d** [comment]
Yeah, I ended up matching it in the end, but it's not perfect. I still have small issues with html inside php not being colored properly. I'll see if I can fix it, and I can submit it if it's ok :)

**Comment by aramk** [comment]
Sure, that would be great.
